# install packages - FSelector, rpart, caret, dplyr, rpart.plot, data.tree, caTools
Sys.setenv(JAVA_HOME = "C:\\Program Files\\Java\\jre")
Sys.getenv('JAVA_HOME')
library(FSelector)
library(rpart)
library(caret)
library(rpart.plot)
library(dplyr)
library(data.tree)
library(caTools)
library(ElemStatLearn)
df = read.csv(file = "income.csv", header = TRUE, check.names = FALSE)
names(df)
df = select(df,'income', 'age', 'fnlwgt', 'education-num' , 'marital-status', 'occupation', 'capital-gain', 'capital-loss', 'hours-per-week')
set.seed(123)
sample = sample.split(df$income,SplitRatio = .85)
train = subset(df, sample == TRUE)
test = subset(df, sample == FALSE)
tree = rpart(income ~ ., data = train)
tree.predict = predict(tree, test, type = 'class')
confusionMatrix(tree.predict, test$income)
prp(tree)


