Sys.setenv(JAVA_HOME = "C:\\Program Files\\Java\\jre")
library(dplyr)
library(caTools)
library(caret)
library(class)
df = read.csv(file = "income.csv", header = TRUE, check.names = FALSE)
names(df)
df$income = as.numeric(df$income)
df$`marital-status` = as.numeric(df$`marital-status`)
df$occupation = as.numeric(df$occupation)
df = select(df,'income', 'age', 'fnlwgt', 'education-num' , 'marital-status', 'occupation', 'capital-gain', 'capital-loss', 'hours-per-week')
sample = sample.split(df$income,SplitRatio = .85)
train = subset(df, sample == TRUE)
test = subset(df, sample == FALSE)
model = knn(train = train, test = test, cl = train$income , k = 21)
confusionMatrix(table(model, test$income))

