Sys.setenv(JAVA_HOME = "C:\\Program Files\\Java\\jre")
library(e1071)
library(dplyr)
library(caTools)
library(caret)
df = read.csv(file = "income.csv", header = TRUE, check.names = FALSE)
names(df)
df = select(df,'income', 'age', 'fnlwgt', 'education-num' , 'marital-status', 'occupation', 'capital-gain', 'capital-loss', 'hours-per-week')
sample = sample.split(df$income,SplitRatio = .85)
train = subset(df, sample == TRUE)
test = subset(df, sample == FALSE)
model = svm(income ~ ., data = train, kernel = "linear")
pred = predict(model, test)
confusionMatrix(pred, test$income)
plot(model,train)
